### ISSUE TITLE
cookie issues between different ynh instances

### ISSUE THREAD

**Issue by julienmalik** [YunoHost/SSOwat#22]
i have one ynh instance on mydomain.tld
i have installed another ynh instance on other.mydomain.tld

the cookies for mydomain.tld interfere with the cookies for other.mydomain.tld
i cannot connect to  other.mydomain.tld without deleting cookies first.
i cannot be loggued in both sso.

**Comment by opi** [comment]
From http://en.wikipedia.org/wiki/HTTP_cookie#Domain_and_Path

- When no "Domain=foo.com" is specified in the cookie, then the cookie will be sent by default for requests to foo.com
- When setting "Domain=foo.com" is sepecified, the cookie will be sent for requests to foo.com AND every subdomain.

My opinion is that we should remove the "Domain=" from cookie string, in https://github.com/Kloadut/SSOwat/blob/unstable/helpers.lua#L104

**Comment by alexAubin** [comment]
Moved to https://dev.yunohost.org/issues/880
