### ISSUE TITLE
Trier les app par catégories / Sort app by category

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost/SSOwat#23]
Trier les applications par catégories afin de les classer dans le portail SSO, ceci afin de donner plus de clarté au portail, pouvoir les retrouver plus facilement et également aider les plus novices à retrouver les applications dont le nom n'est pas toujours explicite.

Dans le principe, les applications définiraient leur(s) catégorie(s) dans le manifest.

Il a été émis l'idée, afin de ne pas impacter les installations avec très peu d'applications, de lier cet affichage par catégories à un bouton sur l'interface.

Des infos en plus sur le pad:
http://pad.thomaslebeau.fr/p/ynh_apps

Le principe pourrait éventuellement être étendu à l'admin et particulièrement la liste des app à installer. Ceci afin d'éviter une surcharge d'applications, le nombre d'app en préparation étant relativement important.

---

Sort apps by categories to classify in SSO portal, in order to give more clarity to the portal, find them more easily and also help the novice find applications whose name is not always explicit.

In "principle", applications define their category(ies) in the manifest.

It has been suggested in order to avoid impacting systems with very few applications to link this category view to a button on the interface.

More information on the pad:
http://pad.thomaslebeau.fr/p/ynh_apps

The "principle" could potentially be extended to the admin and especially the list of app to install. This is to avoid an overload of applications, the number of app in preparation is relatively important.

**Comment by chtixof** [comment]
Hello.
I suggest to sort the apps just alphabetically. Here is a possible solution: https://forum.yunohost.org/t/have-your-apps-sorted-in-the-yunohost-panel/597
Cheers.
ChtiXof

**Comment by alexAubin** [comment]
Moved to https://dev.yunohost.org/issues/881
