### ISSUE TITLE
Nice to have a parameter to set the default page for unauthorized pages

### ISSUE THREAD

**Issue by chtixof** [YunoHost/SSOwat#26]
Present situation:
When a URL is unauthorized, the login URL is displayed

Suggested improvement:
Define a new parameter "Default_URL_when_unauthorized" that tells the URL to redirect to in case of unauthorized page. The default value is the login URL.

This can be used for exemple to redirect to the home page. In this case, the user has to know the exact URL of the login page to be able to sign in.

**Comment by alexAubin** [comment]
Moved to https://dev.yunohost.org/issues/882
