### ISSUE TITLE
Skipped 404 HTTP error on missing files redirect to the login form

### ISSUE THREAD

**Issue by zamentur** [YunoHost/SSOwat#29]
Currently, if I skipped an URL and call an HTTP 404 (like a missing file), I am redirected to the login form (so the skipped_uri instruction is not respected).
I think it shouldn't.

Note: If the file exists, but this file sent a 404 HTTP error inside is code, in this case it's ok I receive the 404 HTTP error.

**Comment by opi** [comment]
Should be fixed by https://github.com/Kloadut/SSOwat/pull/57 , but I would appreciate your point of view.

**Comment by alexAubin** [comment]
Moved to https://dev.yunohost.org/issues/883
