### ISSUE TITLE
When changing of IP, login is necessary again

### ISSUE THREAD

**Issue by ZeHiro** [YunoHost/SSOwat#41]
Hello,

I noticed that even if the session cookie is still OK for a session, when changing of IP (changer of network 3G->Wifi as an exemple), I need to reconnect because SSOWAT considers the session to be not OK anymore. Shouldn't this be transparent for the user?

**Comment by ZeHiro** [comment]
After reading the code this seams to be a feature...

**Comment by Kloadut** [comment]
It was actually a security feature in the first place. But this is not relevent anymore in my opinion.

**Comment by ZeHiro** [comment]
I am not comptetent enough to confirm if it is or not relevant anymore...

**Comment by ZeHiro** [comment]
Any news on that problem?

**Comment by opi** [comment]
Both stable (https://github.com/Kloadut/SSOwat/blob/stable/helpers.lua#L114) and unstable (https://github.com/Kloadut/SSOwat/blob/unstable/helpers.lua#L114) version still use IP address in the cookie hash.

I don't know if it's a security flaw to remove IP address from cookie hash, I'd like to hear from someone competent before removing this line of code.

**Comment by opi** [comment]
It seems that having IP in hash prevent from cookie from being stolen (cookie hijack)

**Comment by Kloadut** [comment]
Yes it is another security policy, but we should make it optional

**Comment by ZeHiro** [comment]
As https is enforced, privacy between client and sever should be ensured, so cookie hijack would require physical access to the client.

**Comment by alexAubin** [comment]
Moved to https://github.com/YunoHost/SSOwat/issues/41
