### ISSUE TITLE
Cannot unprotect a regex/url which is inside a protected path

### ISSUE THREAD

**Issue by jeromelebleu** [YunoHost/SSOwat#43]
Due to this check https://github.com/Kloadut/SSOwat/blob/unstable/access.lua#L245 it is not possible to define an **unprotected_url/regex** for a path that is inside a **protected_url/regex**.

Is it the goal? If yes, how to bypass that? And if not, how to properly fix that? Thanks!

**Comment by Kloadut** [comment]
Good catch. Yes protected url/regex are applied after all the rules.

There is no way to bypass it right now. A good enhancement would be to count the "/" in the path and deduce if a path is a subpath of another one.

**Comment by Djip007** [comment]
Or change (add) more flexible access_control.
for exemple something like filter_url/regex vith 2 parameters:
 - the uti/regex
 - the resulte of the filter: allowed / possibly_allowed / normaly_denny / denny

we then passe all filter. if a filter matche the url/regx and:
  - allowed is use for the filter don't seach anymore accepte
  - denny is use for the filter don't seach anymore denny
  - possibly_allowed tag url as possible and contine with other filter
  - normaly_denny  tag url as denny and contine with other filter

at the end if the url is tag possible  => accepte if not denny 

That way the "short" url is tag normaly_denny... and the longest is tag allowed 

we can add filter priority to assure the order we look throw the filters.

so:
 filter_url/regex {
 "url/regex":
 priority : (0->N)
 resulte : [allowed / possibly_allowed / normaly_denny / denny]
}

I'am not sure but with priority we may remouve allowed /denny.. and anly use  possibly_allowed / normaly_denny... have to thing of it a little bit ;)

**Comment by alexAubin** [comment]
Moved to https://dev.yunohost.org/issues/884
