### ISSUE TITLE
Attempt to index global 'json' (a nil value)

### ISSUE THREAD

**Issue by voidabhi** [YunoHost/SSOwat#64]
This error is thrown at this [line](https://github.com/YunoHost/SSOwat/blob/unstable/config.lua#L13)
Adding 
```
local json = require('json')
```
is fixing it.
Am i missing something here?

**Comment by opi** [comment]
Already done in https://github.com/YunoHost/SSOwat/blob/unstable/init.lua#L18

This file is called by nginx at a global level in /etc/nginx/conf.d/ssowat.conf ( https://github.com/yunohost/yunohost/blob/unstable/data/templates/nginx/plain/ssowat.conf#L2 )

**Comment by voidabhi** [comment]
@opi resolved it. Was calling the init script in wrong scope. Thanks!
