### ISSUE TITLE
Problem when deleting account and user deleted was connected

### ISSUE THREAD

**Issue by tbille** [YunoHost/SSOwat#66]
**Story :**
- Create User A
- Connect with User A
- Delete User A
- Reload page : Error 500 (or nginx default index.html page)

**Problem :**
The cookie is still in the browser. To fix it I have to manually delete the cookies from my browser.
We should be redirected on the connection page.

**Comment by M5oul** [comment]
Hi, thanks for the ticket.
Could you move your ticket to our [bugtracker](https://dev.yunohost.org/projects/yunohost/issues/new).

Thanks.

**Comment by tbille** [comment]
done : [Issue 631](https://dev.yunohost.org/issues/631)

**Comment by M5oul** [comment]
Thanks.
